DOMAIN = "sinum"
MANUFACTURER = "TECH Sterowniki"

# Config entry keys
CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_API_TOKEN = "api_token"
CONF_AUTH_MODE = "auth_mode"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_MQTT_ENABLED = "mqtt_enabled"
CONF_MQTT_TOPIC_PREFIX = "mqtt_topic_prefix"
CONF_MQTT_SCENE_ID = "mqtt_scene_id"
CONF_MQTT_CLIENT_ID = "mqtt_client_id"
CONF_WS_ENABLED = "ws_enabled"
CONF_WS_PATH = "ws_path"
CONF_MAX_CONCURRENT_REQUESTS = "max_concurrent_requests"

# Auth modes
AUTH_MODE_TOKEN = "token"
AUTH_MODE_PASSWORD = "password"

DEFAULT_SCAN_INTERVAL = 30
DEFAULT_MQTT_TOPIC_PREFIX = "sinum"
DEFAULT_MQTT_SCENE_ID = 1
DEFAULT_MQTT_CLIENT_ID = 1
DEFAULT_WS_PATH = "/api/v1/ws"
# Conservative default — some hub embedded firmware can't handle parallel
# request load well. Increase via the options flow for more capable hubs.
DEFAULT_MAX_CONCURRENT_REQUESTS = 2

# REST API — all paths include /api/v1 prefix
API_LOGIN = "/api/v1/login"
API_REFRESH = "/api/v1/refresh"
API_INFO = "/api/v1/info"
API_ROOMS = "/api/v1/rooms"
API_FLOORS = "/api/v1/floors"
API_PARENT_DEVICES = "/api/v1/parent-devices"
API_VIRTUAL_DEVICES = "/api/v1/devices/virtual"
API_WTP_DEVICES = "/api/v1/devices/wtp"
API_SBUS_DEVICES = "/api/v1/devices/sbus"
API_SLINK_DEVICES = "/api/v1/devices/slink"
API_VIRTUAL_DEVICE = "/api/v1/devices/virtual/{id}"
API_WTP_DEVICE = "/api/v1/devices/wtp/{id}"
API_SBUS_DEVICE = "/api/v1/devices/sbus/{id}"
API_SLINK_DEVICE = "/api/v1/devices/slink/{id}"
API_SCENES = "/api/v1/scenes"
API_SCENE = "/api/v1/scenes/{id}"
API_SCENE_LUA = "/api/v1/scenes/{id}/lua"
API_SCENE_LUA_EXTENSIONS = "/api/v1/scenes/{id}/lua-extensions"
API_SCENE_SCHEMA = "/api/v1/scenes/{id}/schema"
API_SCENE_LOGS = "/api/v1/scenes/{id}/logs"
API_AUTOMATIONS = "/api/v1/automations"
API_AUTOMATION = "/api/v1/automations/{id}"
API_AUTOMATION_LUA = "/api/v1/automations/{id}/lua"
API_AUTOMATION_LUA_EXTENSIONS = "/api/v1/automations/{id}/lua-extensions"
API_AUTOMATION_SCHEMA = "/api/v1/automations/{id}/schema"
API_AUTOMATION_LOGS = "/api/v1/automations/{id}/logs"
API_VARIABLES = "/api/v1/variables"
API_VARIABLE = "/api/v1/variables/{id}"
API_NOTIFICATIONS = "/api/v1/notify"
API_WEATHER = "/api/v1/weather"
API_ENERGY = "/api/v1/energy"
API_SCHEDULES = "/api/v1/schedules"
API_SCHEDULE = "/api/v1/schedules/{id}"
API_ENERGY_CENTER_ASSOCIATIONS = "/api/v1/energy-center/associations"
API_ENERGY_CENTER_FLOW_MONITOR = "/api/v1/energy-center/flow-monitor"
API_ENERGY_CENTER_PRICES = "/api/v1/energy-center/prices"
API_ENERGY_CENTER_PRICES_SETTINGS = "/api/v1/energy-center/prices/settings"
API_ENERGY_CENTER_PRICES_SOURCES = "/api/v1/energy-center/prices/sources"
API_ENERGY_CENTER_STORAGE = "/api/v1/energy-center/energy-storage"
API_ENERGY_CENTER_CONSUMPTION = "/api/v1/energy-center/energy-consumption"
API_ENERGY_CENTER_PRODUCTION = "/api/v1/energy-center/energy-production"
API_ALARM_DEVICES = "/api/v1/devices/alarm-system"
API_ALARM_DEVICE = "/api/v1/devices/alarm-system/{id}"
API_ALARM_COMMAND = "/api/v1/devices/alarm-system/{id}/command/{command}"
API_LORA_DEVICES = "/api/v1/devices/lora"
API_LORA_DEVICE = "/api/v1/devices/lora/{id}"
API_MODBUS_DEVICES = "/api/v1/devices/modbus"
API_MODBUS_DEVICE = "/api/v1/devices/modbus/{id}"
API_VIDEO_DEVICES = "/api/v1/devices/video"
API_VIDEO_DEVICE = "/api/v1/devices/video/{id}"
API_VIDEO_SNAPSHOT = "/api/v1/devices/video/{id}/snapshot"
API_VIDEO_STREAM = "/api/v1/devices/video/{id}/stream"
API_SCENE_ACTIVATE = "/api/v1/scenes/{id}/activate"

# Lua HTTP server (sinapse_api.lua — optional, provides wifi/signal data)
API_LUA_INFO = "/api/v1/lua/http-server/sinapse/info"

# Temperature stored as integer × 10 (220 = 22.0 °C)
TEMP_SCALE = 10
TEMP_MIN = 5.0
TEMP_MAX = 35.0

ATTR_SESSION = "session"
ATTR_REFRESH_TOKEN = "refresh_token"

# ── Virtual device types ───────────────────────────────────────────────────────
VTYPE_THERMOSTAT = "thermostat"
VTYPE_RELAY = "relay_integrator"
VTYPE_BLIND = "blind_controller_integrator"
VTYPE_GATE = "gate"
VTYPE_WICKET = "wicket"
VTYPE_DIMMER_RGB = "dimmer_rgb_controller_integrator"
VTYPE_DIMMER_RGB_INTEGRATOR = "dimmer_rgb_integrator"
VTYPE_THERMOSTAT_OUTPUT_GROUP = "thermostat_output_group"

# ── WTP device types ───────────────────────────────────────────────────────────
WTYPE_TEMP_SENSOR = "temperature_sensor"
WTYPE_HUMIDITY_SENSOR = "humidity_sensor"
WTYPE_CO2 = "co2_sensor"
WTYPE_AIR_QUALITY = "air_quality_sensor"
WTYPE_ENERGY_METER = "energy_meter"
WTYPE_LIGHT_SENSOR = "light_sensor"
WTYPE_PRESSURE_SENSOR = "pressure_sensor"
WTYPE_FLOOD_SENSOR = "flood_sensor"
WTYPE_MOTION_SENSOR = "motion_sensor"
WTYPE_OPENING_SENSOR = "opening_sensor"
WTYPE_SMOKE_SENSOR = "smoke_sensor"
WTYPE_TWO_STATE_INPUT_SENSOR = "two_state_input_sensor"
WTYPE_TEMPERATURE_REGULATOR = "temperature_regulator"
WTYPE_FAN_COIL = "fan_coil"
WTYPE_FAN_COIL_V2 = "fan_coil_v2"
WTYPE_RELAY = "relay"
WTYPE_BLIND_CONTROLLER = "blind_controller"
WTYPE_DIMMER = "dimmer"
WTYPE_RGB_CONTROLLER = "rgb_controller"
WTYPE_IAQ_SENSOR = "iaq_sensor"
WTYPE_AQ_SENSOR = "aq_sensor"

# ── SBUS device types ──────────────────────────────────────────────────────────
STYPE_FAN_COIL = "fan_coil"
STYPE_HUMIDITY_SENSOR = "humidity_sensor"
STYPE_TEMPERATURE_SENSOR = "temperature_sensor"
STYPE_TWO_STATE_INPUT_SENSOR = "two_state_input_sensor"
STYPE_RELAY = "relay"
STYPE_DIMMER = "dimmer"
STYPE_RGB_CONTROLLER = "rgb_controller"
STYPE_MOTION_SENSOR = "motion_sensor"
STYPE_LIGHT_SENSOR = "light_sensor"
STYPE_ANALOG_INPUT = "analog_input"
STYPE_IMPULSE_METER = "impulse_meter"
STYPE_BUTTON = "button"
STYPE_ANALOG_OUTPUT = "analog_output"
STYPE_VALVE_PUMP = "valve_pump"
STYPE_COMMON_VALVE = "common_valve"
STYPE_PWM = "pulse_width_modulation"
STYPE_BLIND_CONTROLLER = "blind_controller"
STYPE_ENERGY_METER = "energy_meter"
STYPE_TEMPERATURE_REGULATOR = "temperature_regulator"

WTYPE_BUTTON = "button"

# ── LoRa device types ──────────────────────────────────────────────────────────
LTYPE_TEMP_SENSOR = "temperature_sensor"
LTYPE_HUMIDITY_SENSOR = "humidity_sensor"
LTYPE_OPENING_SENSOR = "opening_sensor"
LTYPE_FLOOD_SENSOR = "flood_sensor"
LTYPE_RELAY = "relay"
LTYPE_TWO_STATE_INPUT_SENSOR = "two_state_input_sensor"
LTYPE_SMOKE_SENSOR = "smoke_sensor"

VTYPE_HEAT_PUMP_MANAGER = "heat_pump_manager"

# ── Gate states ────────────────────────────────────────────────────────────────
GATE_STATE_OPEN = "open"
GATE_STATE_OPENING = "opening"
GATE_STATE_CLOSED = "closed"
GATE_STATE_CLOSING = "closing"
GATE_STATE_MOVING = "moving"
GATE_STATE_NO_MOVE = "no_move"

# ── Wicket states ──────────────────────────────────────────────────────────────
WICKET_STATE_LOCKED = "locked"
WICKET_STATE_UNLOCKED = "unlocked"
WICKET_STATE_OPEN = "open"
WICKET_STATE_CLOSED = "closed"

# ── Notification service ───────────────────────────────────────────────────────
SERVICE_SEND_NOTIFICATION = "send_notification"
ATTR_NOTIFICATION_TITLE = "title"
ATTR_NOTIFICATION_MESSAGE = "message"
SERVICE_UPDATE_SCHEDULE = "update_schedule"
ATTR_ENTRY_ID = "entry_id"
ATTR_SCHEDULE_ID = "schedule_id"
ATTR_PAYLOAD = "payload"
SERVICE_UPLOAD_MQTT_BRIDGE = "upload_mqtt_bridge"
ATTR_MQTT_SCENE_ID = "scene_id"
ATTR_MQTT_CLIENT_ID = "mqtt_client_id"
ATTR_MQTT_DRY_RUN = "dry_run"
SERVICE_RUN_SCENE = "run_scene"
ATTR_RUN_SCENE_ID = "scene_id"
