#!/usr/bin/env python
"""Validate per-module coverage quality gates.

This script checks that critical modules meet their coverage thresholds.
Intended to be run during CI after coverage report generation.

Usage:
    python scripts/validate_coverage_gates.py

Environment:
    - Requires coverage.xml in the workspace root (generated by pytest --cov)
    - Sets exit code 1 if any module fails its threshold
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Define hard per-module coverage thresholds (%).
# Format: module_path: min_threshold
MODULE_THRESHOLDS = {
    "custom_components/sinum/api.py": 100,
    "custom_components/sinum/light.py": 100,
    "custom_components/sinum/cover.py": 100,
    "custom_components/sinum/sensor_virtual.py": 100,
    "custom_components/sinum/coordinator.py": 100,
    "custom_components/sinum/__init__.py": 100,
    "custom_components/sinum/config_flow.py": 100,
    "custom_components/sinum/climate.py": 100,
    "custom_components/sinum/switch.py": 100,
    "custom_components/sinum/websocket.py": 100,
    "custom_components/sinum/lifecycle.py": 100,
    "custom_components/sinum/sensor_modbus.py": 100,
    "custom_components/sinum/services.py": 100,
}

GLOBAL_THRESHOLD = 100


def _normalize_filename(filename: str) -> str:
    """Normalize coverage filenames to repository-relative POSIX paths."""
    normalized = filename.replace("\\", "/")
    marker = "custom_components/sinum/"
    if marker in normalized:
        return normalized[normalized.index(marker) :]
    if normalized.startswith("sinum/"):
        return f"custom_components/{normalized}"
    if "/" not in normalized and normalized.endswith(".py"):
        return f"{marker}{normalized}"
    return normalized


def parse_coverage_xml(xml_path: Path) -> dict[str, float]:
    """Parse coverage.xml and extract per-file coverage percentages."""
    if not xml_path.exists():
        print(f"❌ coverage.xml not found at {xml_path}")
        print("   Run: pytest --cov=custom_components/sinum --cov-report=xml")
        sys.exit(1)

    tree = ET.parse(xml_path)
    root = tree.getroot()

    coverage_by_file = {}
    for package in root.findall(".//package"):
        for cls in package.findall(".//class"):
            filename = cls.get("filename")
            line_rate = float(cls.get("line-rate", 0)) * 100

            if filename:
                coverage_by_file[_normalize_filename(filename)] = line_rate

    return coverage_by_file


def validate_gates(coverage_by_file: dict[str, float]) -> bool:
    """Validate that all modules meet their thresholds."""
    failed_modules = []
    global_failed = False

    print("\n📊 Per-Module Coverage Validation\n")
    print(f"{'Module':<50} {'Coverage':<12} {'Threshold':<12} {'Status'}")
    print("─" * 90)

    for module, threshold in sorted(MODULE_THRESHOLDS.items()):
        actual = coverage_by_file.get(module, 0)
        status = "✅" if actual >= threshold else "❌"

        print(f"{module:<50} {actual:>10.1f}% {threshold:>10}% {status}")

        if actual < threshold:
            failed_modules.append((module, actual, threshold))

    # Global gate
    if coverage_by_file:
        global_coverage = sum(coverage_by_file.values()) / len(coverage_by_file)
        status = "✅" if global_coverage >= GLOBAL_THRESHOLD else "❌"
        print("─" * 90)
        print(f"{'GLOBAL':<50} {global_coverage:>10.1f}% {GLOBAL_THRESHOLD:>10}% {status}")
        global_failed = global_coverage < GLOBAL_THRESHOLD

    print()

    if failed_modules:
        print("❌ Modules below hard coverage threshold:\n")
        for module, actual, threshold in failed_modules:
            gap = threshold - actual
            print(f"   {module}: {actual:.1f}% (threshold {threshold}%, gap {gap:.1f}%)")
        print()

    if global_failed:
        print(f"❌ Global average coverage is below {GLOBAL_THRESHOLD}%.\n")

    return not failed_modules and not global_failed


def main():
    """Main entry point."""
    workspace_root = Path(__file__).parent.parent
    coverage_xml = workspace_root / "coverage.xml"

    coverage_by_file = parse_coverage_xml(coverage_xml)
    passed = validate_gates(coverage_by_file)

    if passed:
        print("✅ Coverage gates passed.\n")
        sys.exit(0)

    print("❌ Coverage gates failed.\n")
    sys.exit(1)


if __name__ == "__main__":
    main()
