name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          cd custom_components
          zip -r ../sinum.zip sinum/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: sinum.zip
          generate_release_notes: true
